### ISSUE TITLE
Characters removed after completion

### ISSUE THREAD

**Issue by Krakonos** [prabirshrestha/asyncomplete.vim#156] opened 2019-08-13 09:47 UTC
Hi!

I'm running asyncomplete with asyncomplete-lsp and found this issue when using completion for function parameter.

```
int foo(int a, int b) {
	return a+b;
}

int main() {
	int MY_LONG_VARIABLE;
	foo(1, 0)
}
```

For example, if I try to replace the "1" argument with "MY_LONG_VARIABLE", I end up with the following code after completion:
```
int foo(int a, int b) {
	return a+b;
}

int main() {
	int MY_LONG_VARIABLE;
	foo(MY_LONG_VARIABLE
}
```

Here is the example withv vim (8.1.1776) and neovim (0.3.8) in action:
![issue-removal-2019-08-13_11 35 23](https://user-images.githubusercontent.com/138209/62932145-e468fe00-bdbf-11e9-83f7-28815f2c103d.gif)

My init.vim is very basic (I reduced it from my usual configuration, lsp_virtual_text_enabled is not necessary, but makes the demo much cleaner

):
```
set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
let g:lsp_virtual_text_enabled = 0
if executable('ccls')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'ccls',
      \ 'cmd': {server_info->['ccls']},
      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
      \ 'initialization_options': {'cache': {'directory': '/tmp/ccls/cache' }},
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc', 'h', 'hpp'],
      \ })
endif

call plug#end()
```

(attaching this, my main.cpp and compile_commands.json in the zip file).

Is this a desirable feature I don't know the name for, or is it a bug? Anyway, I'd appreciate if it could be turned off/fixed.

Thanks!
Ladislav

[issue-setup.zip](https://github.com/prabirshrestha/asyncomplete.vim/files/3496353/issue-setup.zip)

**Comment by sxyu** [comment] 2019-08-24 21:59
this always happens for me as well and is extremely annoying

**Comment by thenewvu** [comment] 2019-08-25 04:40
It happens to me too. Seems supporting for textEdit is unstable: https://github.com/prabirshrestha/vim-lsp/issues/142

I set `let g:lsp_text_edit_enabled = 0` in my rc to workaround this.

**Comment by mattn** [comment] 2019-09-07 11:31
Yes, I guess this is problem of vim-lsp. When CompleteDone occur, the text is filled by selected candidate text already. So it don't need to modify. Any thoughts? @prabirshrestha

**Comment by prabirshrestha** [comment] 2019-09-07 22:44
@mattn Here was some investigations I had done before. https://github.com/prabirshrestha/vim-lsp/issues/328#issuecomment-492646814

**Comment by prabirshrestha** [comment] 2019-09-08 16:59
This is a bug in vim-lsp so please file the issue there. Closing this issue here.

**Comment by thenewvu** [comment] 2019-09-10 15:11
I tested vim-lsp without asyncomplete (by `setlocal omnifunc=lsp#complete`), the issue doesn't happen, so it indeed relates to asyncomplete. Could you please reopen this and give sometime to investigate it.

Below are some logs I tested on the issue author's sample project:
[vim-lsp.log](https://github.com/prabirshrestha/asyncomplete.vim/files/3596413/vim-lsp.log)
[asyncomplete.log](https://github.com/prabirshrestha/asyncomplete.vim/files/3596414/asyncomplete.log)

**Comment by prabirshrestha** [comment] 2019-09-10 15:19
Reopening. Can you provide a simple repel steps. I have noticed this too but can’t reproduce easily to debug further.

**Comment by thenewvu** [comment] 2019-09-10 15:27
Let try the author sample project in the issue-setup.zip, I think it's simple enough.

Steps:

```
	foo(M|)
```
At this moment, asyncompelte should display some completions, <C-n> or <C-p> to select any, then <esc>:
```
	foo(MY_LONG_VARIABLE
```

Notive the `)` has removed.

![asyncomplete-issue-482](https://user-images.githubusercontent.com/6092585/64627346-aa6c3580-d419-11e9-9283-b6dfe6106dbc.gif)

**Comment by prabirshrestha** [comment] 2019-09-10 16:51
@thomasfaingnaert I'm wondering if we need to do something like this here in asyncomplete-lsp. https://github.com/prabirshrestha/vim-lsp/issues/291#issuecomment-462064628.

Most likely we are not generating the same complete items in asyncomplete-lsp compared to vim-lsp omnifunc.
https://github.com/prabirshrestha/asyncomplete-lsp.vim/blob/master/plugin/asyncomplete-lsp.vim#L88

**Comment by thenewvu** [comment] 2019-09-10 17:46
It doesn't seem wrong, but .. I have tried on neovim 0.3.8, the issue happens on it too.

**Comment by thomasfaingnaert** [comment] 2019-09-10 17:50
I'm on
```
NVIM v0.4.0-1809-ge3e0574cb
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/thomas/src/neovim/build/config -I/home/thomas/src/neovim/src -I/home/thomas/src/neovim/.deps/usr/include -I/usr/include -I/home/thomas/src/neovim/build/src/nvim/auto -I/home/thomas/src/neovim/build/include
Compiled by thomas@dell-xps

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
Should I downgrade?

**Comment by thenewvu** [comment] 2019-09-10 17:51
No, I'm using neovim 0.4 too, just switched to 0.3.8 to eliminate the case.

**Comment by thomasfaingnaert** [comment] 2019-09-10 17:52
I'll wipe my config and try again.

**Comment by thomasfaingnaert** [comment] 2019-09-10 17:59
![Peek 2019-09-10 19-58](https://user-images.githubusercontent.com/10748726/64638123-7be45f80-d405-11e9-8409-d3d3b61e77b7.gif)
Same result :(
How consistent can you reproduce it on your machine?

**Comment by thenewvu** [comment] 2019-09-10 18:05
Everytime I tried with that said simple steps so far.

**Comment by mattn** [comment] 2019-09-11 00:32
I can reproduce this. 

![terminal7](https://user-images.githubusercontent.com/10111/64659462-e71a4a00-d476-11e9-83a0-ed5530cdea62.gif)

And this don't reproduce with `let g:lsp_text_edit_enabled = 0`

**Comment by prabirshrestha** [comment] 2019-09-11 00:47
I'm wondering if this is due to vim adding the text once the completion finishes and text edit getting applied after the completion.

**Comment by mattn** [comment] 2019-09-11 00:48
>I'm wondering if this is due to vim adding the text once the completion finishes and text edit getting applied after the completion.

Yes, right. happen as you are thinking.

**Comment by thomasfaingnaert** [comment] 2019-09-11 10:58
Tried this again with clangd 8, I can now also reproduce this.
Did some digging around, and I think I know the problem:
https://github.com/prabirshrestha/vim-lsp/blob/34397f0b5f72c058c6806cff88f82d055958146c/autoload/lsp/omni.vim#L349-L354

In the asyncomplete case, `v:completed_item` is `MY_LONG_VARIABLE`, so the `expand_length` is 16 instead of 14, resulting in two characters at the end to be overwritten.

For omnifunc, `v:completed_item` only contains what is typed from the moment completion was invoked, i.e. `_LONG_VARIABLE`, so everything works correctly.

I guess what we need is a way to obtain the number of extra characters inserted after Vim fills in the completion item, compared to how the buffer looked like when `textDocument/completion` was sent.
Alternatively, save the current line and restore if before applying text edits? (Sounds hacky, though)

**Closed** 2020-10-24 19:40 UTC
Labels: bug, wontfix
